spring:
    datasource:
        url: jdbc:postgresql://db:5432/geolesson
        username: geolesson_user
        password: geolesson_user
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update

logging:
    level:
        org:
            springframework:
                security: DEBUG
                web: DEBUG